# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmimage: Ubuntu 16.04

steps:
  - task: InstallMATLAB@0
    inputs:
      release: R2020a

  - task: RunMATLABTests@0
    inputs:
      codeCoverageCobertura: 'code-coverage/coverage.xml'
      selectByFolder: 'testing/testarchive/'
      sourceFolder: 'lib:models:setup'
      testResultsJUnit: 'test-results/results.xml'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results/results.xml'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'code-coverage/coverage.xml'
